### PR TITLE
Update report.csv

### PR DESCRIPTION
**Pull request by nkvenom**
Added monoku, it's a development shop but has its own product called monomi.co

### CODE REVIEW

**Comment by buritica** [comment]
Thanks @nkvenom, this is tricky territory. I'm not sure if `monomi` is incorporated as a separate company? They are close friends of mine, but I'm trying to be objective here. I'd be willing to add monomi if it had a separate github account under which they contributed stuff produced from monomi to open source. I'd do the same for Koombea, and any other shops that have other products.

I think unless this is a common occurring, I'm going to pass on it for now.

Thanks for the contribution though!

**Comment by nkvenom** [comment]
Ok, thanks for answering, what do you think of mejorandola/platzi, will they classify?. They have several repositories with some of those rounding the hundreds of stars, some of them are code examples but they have libraries like PonyExpress.

**Comment by buritica** [comment]
I think their libraries would count. They are a company that should be in that list since they have colombian founder, and engineering operations there. 

Feel fre to send the PR, don't forget to add them to the summary in the readme.  And if possible I'd appreciate if they are added in alphabetical order. 

Thanks for your contributions

## 

Juan Pablo Buritica

t: @buritica

**Comment by dav009** [comment]
I really like mejorandola, however I wonder whether their "tutorial repos" would really count.

so assume company `X` offers a product `Y` and has lets say 3 or 4 repos where they store clients to their main core product/service i.e: `Javascript client to product Y`, would that really count as Open source contributions?

In that regard I think those `tutorial repos` fall into the same category.

**Comment by buritica** [comment]
I agree. Tutorial repos are part of their product and not meant only as a contribution. 

## 

Juan Pablo Buritica

t: @buritica

**Pull request closed without merging**
